### ISSUE TITLE
"Add note" button in tray menu

### ISSUE THREAD

**Issue by bE7rwls** [dragonwocky/obsidian-tray#10]
Could you add "Add note" button in tray menu, and shortcut for it, if its possible

**Comment by trulycool** [comment]
Before finding this excellent Plugin, I created a very hacky implementation of this [Add Note] feature, which requires both a *.js file (that makes the timestamp, and opens it in Obsidian), and a *.vbs file (to launch the node file in the background w/out spawning a node window that just stays open as long as Obsidian is running.) 

It has several other drawbacks:
- the vault name is hard coded
- windows specific (The VBS portion anyway, the node script is not AFAIK so long as you update your path to Obsidian. There are Linux & Mac specific ways to launch a program in the background, I just haven't sorted them out yet)
- then requires a third file; windows shortcut to the VBS, to which a hotkey / shortcut key can be assigned

Basically it creates a filesystem friendly timestamp, and launches Obsidian with the new switch giving the file the datestamped name. You can easily change or add to the name which is focused when Obsidian opens. Am trying to emulate some classic Tomboy Notes type functionality...

Thinking this basic approach, integrated w/ this plugin would be far superior. I will come back to this when work tapers off a bit and spare time allows...but just in case @dragonwocky gets free time first and dives into these issues before making the changes Obsidian requires to accept into the Community Plugins...

## note.js
 ```
let now = new Date();
let year = now.getFullYear();
let month = String(now.getMonth() + 1).padStart(2, '0');
let day = String(now.getDate()).padStart(2, '0');
let hour = String(now.getHours()).padStart(2, '0');
let minute = String(now.getMinutes()).padStart(2, '0');
let second = String(now.getSeconds()).padStart(2, '0');
let datestamp = `${year}-${month}-${day}_${hour}.${minute}.${second}`;
// console.log(datestamp);
let cmdPath = 'start C:\\Users\\[your-username]\\\AppData\\Local\\Obsidian\\Obsidian.exe';
let command = `${cmdPath} "obsidian://new?vault=obsidian-vault&file=+Inbox/${datestamp}.md"`;
// console.log(command);

var exec = require('child_process').exec;
exec(`START /B C:\\Users\\[your-username]\\AppData\\Local\\Obsidian\\Obsidian.exe "obsidian://new?vault=obsidian-vault&file=+Inbox/${datestamp}.md"`, function (err, stdout, stderr) {
    if (err) {
        throw err;
    }
})
```

## new-note.vbs
```
Dim objShell
Set objShell = WScript.CreateObject("WScript.Shell")
objShell.CurrentDirectory = "C:\Users\[your-username]\\bin\"
objShell.Run("""node"" note.js"), 0
Set objShell = Nothing
```

**Comment by dragonwocky** [comment]
@trulycool thanks! That code looks like a good starting point. I'm planning on making the needed changes sometime in the next couple of weeks, but not sure if I'll be able to include this feature right away. Feel free to open a PR for this if you get a chance \:)

**Comment by dragonwocky** [comment]
@trulycool @bE7rwls added in the latest commit, + some options in the menu to configure the name and location of the created note.

**Comment by trulycool** [comment]
@dragonwocky You are da man!

Beautiful job implementing this, including customization of shortcut & date format for title.

This plugin absolutely belongs in Obsidian Core, let alone Community Plugins.

Dunno what I could offer to help this happen, but happy to try if there is anything...

Thank you so much!
🙏🙌
