### ISSUE TITLE
Add "hide from taskbar" option

### ISSUE THREAD

**Issue by bushnerd** [dragonwocky/obsidian-tray#11]
Could you pls add "hide from taskbar" option in if its possible, it seems no need to display a icon in the taskbar.

**Comment by dragonwocky** [comment]
You can already do this? Just disable the "Create tray icon" option.

**Comment by bushnerd** [comment]
Sorry, this might be a bit ambiguous. I mean this icon in taskbar not tray icon.
![image](https://user-images.githubusercontent.com/28666253/218288878-b22bac03-a3b7-4dcb-9e87-47ee665affb4.png)

**Comment by dragonwocky** [comment]
Ah, gotcha. Could be done, I'll give it a go next time I update.

(Note to self: https://www.electronjs.org/docs/latest/api/browser-window#winsetskiptaskbarskip-macos-windows)

**Comment by darkworks** [comment]
yes pls add this hide from task bar option as its much needed. so that on minimize it directly go to tray instead of display icon etc in taskbar.

**Comment by darkworks** [comment]
@dragonwocky any update on this fix . pls

**Comment by dragonwocky** [comment]
@darkworks @bushnerd added in the latest commit, let me know how it goes.

**Comment by darkworks** [comment]
> @darkworks @bushnerd added in the latest commit, let me know how it goes.

ya its working thanks for the fix..

is there way if we could listen for obsidian top right close button event and override it with this plugin so that instead of obsidian exit through this plugin it hide into tray.  

thanks.

**Comment by dragonwocky** [comment]
@darkworks yes, that's one of the changes that need to be made before this is merged into the official repository (tracked here: https://github.com/obsidianmd/obsidian-releases/pull/1365). Currently closing the window using the Obsidian frame (where the window close button is part of the Obsidian interface) is overridden, but closing the window using the native titlebar isn't yet.

**Comment by darkworks** [comment]
@dragonwocky  ok good to hear , check this it might help : https://medium.com/@onur.polattimur/electron-frameless-window-close-and-minimize-to-tray-5bab47f66f82
