### ISSUE TITLE
Is there a pending process of introducing this plugin into official Obsidian community repository?

### ISSUE THREAD

**Issue by alterdaemon** [dragonwocky/obsidian-tray#12]
why isn't it already there?

**Comment by dragonwocky** [comment]
https://github.com/obsidianmd/obsidian-releases/pull/1365 - there are a few changes that need to be made before it's fully ready for public use, then it'll be merged into the official repository. I've been focusing on a couple of other projects at the moment so haven't gotten around to making those changes yet.

**Comment by dragonwocky** [comment]
All requested changes have been made (+ a few extra improvements), the plugin is now just waiting for review :)

**Comment by pwflint** [comment]
Very excited to integrate this into my system

**Comment by dragonwocky** [comment]
The plugin has now been added to the official community repository.
