### ISSUE TITLE
macos compat: option to auto-disable (e.g. if syncing)

### ISSUE THREAD

**Issue by Frostyyy1997** [dragonwocky/obsidian-tray#15]
Wonderful plugin with Windows. But I used Obsidian Sync (The offical one) and the plugin will lead problem on MacOS; obsidian cannot be run at all.

**Comment by dragonwocky** [comment]
@Frostyyy1997 have you got it set to "hide on launch"? If you open it and it doesn't seem to appear it may be hiding by default, you can try using the hotkey or menubar icon to bring the app into focus.

**Comment by Frostyyy1997** [comment]
> @Frostyyy1997 have you got it set to "hide on launch"? If you open it and it doesn't seem to appear it may be hiding by default, you can try using the hotkey or menubar icon to bring the app into focus.

I didn't explore further, I just disbaled plugin config sync and remain the plugin disabled on my mac and it's fine now.

**Comment by dragonwocky** [comment]
Well, sure, you can disable it if you don't want to use it. I don't have a Mac, though, so if you want me to fix the plugin on Mac you'll need to give me some more information about what's actually happening and the unexpected behaviours/effects of each option of the plugin.

**Comment by Frostyyy1997** [comment]
Yes, if you can fix it, that can help others who use official obsidian sync.

I don’t know much about development but I know on Mac, users don’t need launch at start and tray feature. If you can make the plugin detecting that it was running on MacOS, disable it just like on mobile devices. That’ll be good.

Thanks

**Comment by Frostyyy1997** [comment]
> Yes, if you can fix it, that can help others who use official obsidian sync.
> 
> I don’t know much about development but I know on Mac, users don’t need launch at start and tray feature. If you can make the plugin detecting that it was running on MacOS, disable it just like on mobile devices. That’ll be good.
> 
> Thanks



> Well, sure, you can disable it if you don't want to use it. I don't have a Mac, though, so if you want me to fix the plugin on Mac you'll need to give me some more information about what's actually happening and the unexpected behaviours/effects of each option of the plugin.

Yes, if you can fix it, that can help others who use official obsidian sync.

I don’t know much about development but I know on Mac, users don’t need launch at start and tray feature. If you can make the plugin detecting that it was running on MacOS, disable it just like on mobile devices. That’ll be good.

Thanks

**Comment by dragonwocky** [comment]
@Frostyyy1997 there are other mac users who do want/use those two features, even if you personally don't...

Like I said before, though:
> if you want me to fix the plugin on Mac you'll need to give me some more information about what's actually happening and the unexpected behaviours/effects of each option of the plugin.

Those two features existing is not a bug. If those two features are behaving in a way that breaks the app, that is a bug, but I need you to explain and/or provide screenshots/recordings of what's going wrong to be able to fix them.

> If you can make the plugin detecting that it was running on MacOS, disable it just like on mobile devices.

Sure, I could probably add an option to disable the plugin on specific platforms. I'll do that next time I update this, whenever that is.

**Comment by dragonwocky** [comment]
Coming back to this: I've been working to improve macOS support by fixing the specific bugs reported in other issues. Rather than add a generic kill-all switch, I'd rather fix the actual bugs that exist.

If you can explain to me which features are misbehaving and in what ways, I can fix that, but adding a kill-all switch was proving messy and is a route I'd rather not go down anyway (especially since I don't have a Mac to test on).
