### ISSUE TITLE
Maximized windows are not preserved when "Run in background" is disabled

### ISSUE THREAD

**Issue by jonschz** [dragonwocky/obsidian-tray#22]
First of all, thank you for this really helpful plugin!

**System:** Window 10, Obsidian v1.3.5, Tray v0.3.3

**Steps to reproduce:**
1. Start Obsidian and maximize the window. Disable "Run in background" (if it is enabled).
2. Minimize Obsidian.
3. Make Obsidian reappear via this plugin (click tray icon / Ctrl+Shift+Tab / Ctrl+Shift+Q)

**Expected behaviour:**
- The window should be maximized.

**Actual behaviour:**
- The window is not maximized and defaults to the last non-maximized size it had.

**Further notes:**
- This issue does not appear when "Run in background" is enabled.
- Reopening Obsidian from the task bar (assuming "Hide taskbar icon" is not enabled) does not have this issue.
- This issue is independent of the setting "Hide taskbar icon".

**Comment by Zarpyk** [comment]
It also happens when "Run in background" is enabled, and it only happens when use the "Minimize" button and don't happen with the close button.
