### ISSUE TITLE
Mac: "Hide taskbar icon" setting not working as expected

### ISSUE THREAD

**Issue by youngboy** [dragonwocky/obsidian-tray#27]
When the "Hide Taskbar Icon" setting is enabled, the Obsidian icon still appears in the task switcher and the dock on macOS. Could this be due to the lack of a `app.dock.hide()` call for the macOS platform?

https://www.electronjs.org/docs/latest/api/dock#dockhide-macos

macOS version: 13.4

**Comment by dragonwocky** [comment]
Yes. Yes it could be. Thanks for the pickup - I'm not a mac user myself, so I have no way of testing these things. Interestingly, [`BrowserWindow.setSkipTaskbar()`](https://www.electronjs.org/docs/latest/api/browser-window#winsetskiptaskbarskip-macos-windows) (which I do call) claims that it's macOS compatible, which makes me wonder what it is doing/what differentiates it from `app.dock.hide()`.

**Comment by youngboy** [comment]
maybe this is relate https://github.com/tauri-apps/tauri/issues/4852#issuecomment-1204100382

**Comment by dragonwocky** [comment]
I've pushed a possible fix for this, if you could follow the [manual installation instructions](https://github.com/dragonwocky/obsidian-tray#manual) to test it out before I release it to the Obsidian marketplace that'd be really helpful. Thanks!

**Comment by youngboy** [comment]
the fixes works for me, thanks
