### ISSUE TITLE
Toggle window focus hotkey is triggered twice

### ISSUE THREAD

**Issue by vanbang9710** [dragonwocky/obsidian-tray#29]
Steps to reproduce
- Open sandbox vault
- Install this plugin
- Focus on other window, such as the browser window
- Toggle hotkey
- Nothing happens because the hotkey is triggered twice. May use [HotkeyDetective](https://github.com/ITachiLab/hotkey-detective) to notice this ![|50pct](https://i.imgur.com/qyDINsu.png)

**Comment by dragonwocky** [comment]
@vanbang9710 that's interesting.

I think what you've noticed with HotkeyDetective may be slightly misleading, though- the event registered by the plugin is still only getting triggered once, as you can see in the image below (logged 2x by the shortcut's event handler, 4x by HotkeyDetective). My guess would be that Electron's implementation of global shortcuts is to blame (i.e. it may be detecting both keyup and keydown, even if it only actually calls the handler on one of them).
![image](https://github.com/dragonwocky/obsidian-tray/assets/16874139/56aecc9f-b3b7-4121-b163-21fea9f1c6aa)

Could you please send me a screen recording of what's happening here for you + what your configuration of the plugin is? The toggle window focus hotkey is working perfectly fine for me, both in a sandbox vault and in my own local vault, so I suspect there's likely something else going on here.

**Comment by vanbang9710** [comment]
How do you check the plugin log? 
- The plugin settings 
![image](https://github.com/dragonwocky/obsidian-tray/assets/52906188/9dcce21d-d8b1-4ec6-9a97-6895e31c39cd)

https://github.com/dragonwocky/obsidian-tray/assets/52906188/8fb39c14-6565-4afe-a422-a1376860bd52

**Comment by dragonwocky** [comment]
@vanbang9710 okay, I think I see what you mean, although there was a lot going on there.

I recommend trying a different hotkey and seeing if that works for you - some keyboard layouts/system languages/apps/etc. will transform characters when <kbd>Alt</kbd> is pressed, which can cause issues for hotkeys that contain it. E.g. you can be pressing <kbd>Alt + E</kbd>, but by the time it gets to this plugin, it may have actually ended up as <kbd>É</kbd> instead (or something similar).

(You can open the console via `Ctrl+Shift+I` and check the logs there. The coloured text is something I added during testing, but the installable version does log every action via the white text.)

**Comment by vanbang9710** [comment]
I try Ctrl+q and q but still no luck. In the console, it does show only 1 event each time I press.

**Comment by dragonwocky** [comment]
@vanbang9710 hm, I see. Well, if the events are being logged in the console properly then it's not a hotkey-related issue, but something to do with the window actually getting focus... but I can't replicate it, so I don't really know how to fix it/what I'm actually fixing. If you can work out what might be causing it (e.g. some conflict with another app you have running?) I may be able to give fixing it a go, but until then there's not a lot I can do, sorry.

**Comment by dragonwocky** [comment]
Fixed in 0.3.5 (just released) - it was specifically related to the preservation of maximised windows that was added in 0.3.4. I couldn't reproduce this originally because I was testing with the app windowed/not maximised, sorry about that.
