### ISSUE TITLE
[Request] Close to tray except on startup

### ISSUE THREAD

**Issue by IzMichael** [dragonwocky/obsidian-tray#4]
Hiya, I'd like to be able to decouple the "Minimise to Tray on Startup" from the "Minimise to Tray on Close" feature. I'd like to keep Obsidian open when it starts, but minimise to tray when I close it. Is this possible?
Thanks!

**Comment by AAndyProgram** [comment]
I have the same request and thank you for your plugin.

**Comment by AAndyProgram** [comment]
Thank you! Works great!
