### ISSUE TITLE
Tray icon does not have label / tag.

### ISSUE THREAD

**Issue by Reginald-Gillespie** [dragonwocky/obsidian-tray#44]
![image](https://github.com/dragonwocky/obsidian-tray/assets/109245101/4142abbe-2478-4261-923b-5f4f04fbfc87)

You can see in this screenshot that at least for Plasma 6, the tray icon does not have a label. Wouldn't see this as too big of an issue typically except that discord has the same issue, and then plasma 6 has another issue where icons of the same name are hidden or shown together, which means I can't hide obsidian while showing discord.

**Comment by dragonwocky** [comment]
Hmm, if Discord and obsidian-tray are both having this issue then the common factor may be Electron. Are you able to confirm for me if tray labels do work for any other Electron apps?
- If you can't find any that work, then it's a bug that should be reported to https://github.com/electron/electron/issues.
- If you can find one that works, I may be able to copy the way they initialise their tray to fix the bug for obsidian-tray.

Thanks!

**Comment by Reginald-Gillespie** [comment]
Oh, you're right, I didn't even realize that Obsidian used electron. Yeah there does seem to be some discussion about it: https://github.com/electron/electron/issues/40936

I'll check out a few apps to see if any find a workaround but otherwise I assume this'll just have to wait until electron fixes it.
