### ISSUE TITLE
Compatibility with macOS

### ISSUE THREAD

**Issue by phlind** [dragonwocky/obsidian-tray#5]
I use the plugin on Windows and it works fine, but when I open my vault on macOS, Obsidian is hidden without the possibility to make the window appear, since there is no menu bar icon. 

Could you add compatibility with macOS, or if not possible, at least deactivate the plugin automatically when a vault is opened on macOS? Thanks!

**Comment by dragonwocky** [comment]
@phlind have you tried using the hotkey to make the window appear on macOS? There should be a menu bar icon, though, that's quite odd that it's not there. I've used the same code to create a tray icon that has appeared for macOS users before. Is there any possibility you would be able to attempt to find a solution to the missing menu bar icon? I don't have a mac myself to do any testing on, unfortunately.

Changes needed to the auto-hiding behaviour of the app are tracked in #4 and #6, I'll update that soon.

**Comment by phlind** [comment]
So, I tried it again, and it worked partly, but not reliably. The menu bar icon did actually show, but not always. I'm not sure why, but it showed for me the first time I opened Obsidian. After quitting Obsidian totally and opening it again, it did not show anymore. (It is a little bit too big for the menu bar as well):

![Bildschirmfoto 2022-12-28 um 17 02 35](https://user-images.githubusercontent.com/30386310/209839535-f30bba0e-941d-4e18-94e4-f6c583b1cd2c.png)

I could use the shortcut to bring back Obsidian, but that stopped working after closing the Obsidian window it with the red button on top. Maybe that has to be avoided on macOS?

**Comment by dragonwocky** [comment]
@phlind do the latest changes to the default behaviour of windows on app launch make the app work more as you would expect on macOS?

**Comment by dragonwocky** [comment]
@phlind I've made a few changes that I think should address all of this, let me know if you have any more problems:
- 16x16 icon instead of 32x32 icon so it should be the right size for the menu bar.
- intercepting window close events at electron level instead of by overriding the button used by Obsidian on windows for non-native titlebars.
- making hide on launch a separately configurable option that is disabled by default.
