### ISSUE TITLE
Feature Request: hide and show per vault?

### ISSUE THREAD

**Issue by hedonihilist** [dragonwocky/obsidian-tray#7]
When the hotkey is pressed, all obsidian windows are hidden. Is is possible to configure hotkey per vault? So that obsidian windows will not interfere with each other.

**Comment by dragonwocky** [comment]
Hmm, maybe. This is a good idea, it may take some work though to figure out how the plugin can tell which windows go with which vaults - I'll have a go at this after I've gotten up to date with a couple of my other projects.

**Comment by dragonwocky** [comment]
@hustrjh yes, I think this is close enough to the same issue. #2 is related as well.

I'm focusing on the [notion-enhancer](https://github.com/notion-enhancer/notion-enhancer) at the moment, but once I've pushed out the update for that I'll see what I can do about this.

**Comment by hustrjh** [comment]
Take your time. Thanks!

**Comment by dragonwocky** [comment]
@hustrjh @hedonihilist multi-vault support has been added in the latest commit/release, let me know how it goes :)

**Comment by hustrjh** [comment]
@dragonwocky  It works perfect for me. Thanks for your excellent work. ❤️

**Comment by hedonihilist** [comment]
@dragonwocky Just tried the new version and it's awesome. Thank you for your work👍
