### ISSUE TITLE
Add shortcut key for “relaunch obsidian”

### ISSUE THREAD

**Issue by irrealizable** [dragonwocky/obsidian-tray#8]
For some reasons, I need to reload obsidian, but this plugin conflicts with the overload function of obsidian

**Comment by dragonwocky** [comment]
Until I add it, does the button in the tray menu do what you need?
![image](https://user-images.githubusercontent.com/16874139/212596907-01f73409-c144-47b6-afdf-d8fd420f5017.png)

**Comment by dragonwocky** [comment]
@irrealizable would assigning a hotkey to this command (built into Obsidian) help you?
![image](https://user-images.githubusercontent.com/16874139/230771312-8e140450-897b-4d77-9fdb-b162b4a18caa.png)

**Comment by dragonwocky** [comment]
@irrealizable added in the latest commit, "relaunch obsidian" can be triggered via the command palette and have a hotkey assigned to it through Obsidian's hotkey manager:
![image](https://user-images.githubusercontent.com/16874139/230817605-48bd68bc-23c9-444b-a658-13a7a734dfa2.png)
